  
---
- hosts: webservers 
  become: True
  tasks:
    - name: Uninstall packages
      yum:
        name: "httpd"
        state: "absent"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: False
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
